# Generated by Django 4.1.1 on 2022-11-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='short_urls',
        ),
    ]
